---
title: "Educational Information"
author: "Alana Santana"
date: '2022-07-06'
output: flexdashboard::flex_dashboard:
     theme: yeti 
     source_code: embed
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Page 1

```{r}
# What is the Endangered Species Act (ESA) and why is it important?

# 	The Endangered Species Act (formerly known as the The Endangered Species Conservation Act of 1969) is the nation’s strongest and most effective law protecting at-risk species from extinction. The ESA was amended and enacted in 1973 and its purpose is to prevent the extinction of threatened plants and animals, increase their numbers to promote full recovery, and eventually be able to remove threatened species from the endangered list. The ESA works by requiring protections for critical habitats and actively monitoring and assessing species numbers through recovery plans facilitated through the Department of Fish and Wildlife Service. This law allows for flexibility in its implementation, requiring coordination among federal, state, tribal, and local officials on efforts to prevent extinction. Currently, more than 1,600 species are under ESA protections.
# 	ESA listings are reviewed every five years to determine whether the species should be reclassified or delisted based on several factors. These factors include: is there a present or threatened destruction, modification, or curtailment of the species’ habitat or range? Is the species subject to over-utilization for commercial, recreational, scientific, or educational purposes? Is disease or predation a factor? Are there adequate existing regulatory mechanisms in place, taking into account the initiatives by States and other organizations, to protect the species or habitat? and are other natural or manmade factors affecting its continued existence? Based on these factors, the U.S Department of Fish and Wildlife Service decides whether or not a species qualifies for delisting.
#   
```

# Page 2

```{r}
#' NOAA Permitting Process
#'
#
```
